openapi: 3.0.0
info:
  title: Example API
  version: 1.0.1
  description: API definition to test Spectral rules
servers: 
  - description: Production
    url: https://api.example.com/v1
security:
  - please-hack-me: []

tags:
- name: API
  description: Foo
paths:
  /not-json:
    get:
      summary: Foo
      description: Bar
      operationId: notJson
      tags: 
      - API
      responses:
        '200':
          description: OK
          content:
            nonsense/json:
              schema:
                type: string
                example: 'hello!'

  /unknown-error:
    get:
      tags: 
      - API
      summary: Your GET endpoint
      description: Your GET endpoint
      operationId: get-endpoint
      responses:
        "200":
          description: Error
          content:
            application/json:
              schema:
                properties:
                  errorDescription:
                    type: string
        "400":
          description: Error
          content:
            application/json:
              schema:
                properties:
                  errorDescription:
                    type: string
                    
components:
  securitySchemes:
    please-hack-me:
      type: http
      scheme: basic
